"""Declarative base, naming conventions and shared column mixins."""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.core.config import settings

# Explicit naming convention so Alembic generates stable, readable constraint
# names instead of PostgreSQL's positional defaults. Without this, autogenerate
# produces migrations that cannot drop the constraints they created.
NAMING_CONVENTION = {
    "ix": "idx_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(
        naming_convention=NAMING_CONVENTION,
        schema=settings.POSTGRES_SCHEMA,
    )

    def to_dict(self, exclude: set[str] | None = None) -> dict[str, Any]:
        skip = exclude or set()
        return {
            c.key: getattr(self, c.key)
            for c in self.__table__.columns
            if c.key not in skip
        }

    def __repr__(self) -> str:
        pk = self.__mapper__.primary_key[0].key
        return f"<{type(self).__name__} {pk}={getattr(self, pk, None)}>"


class UUIDPrimaryKeyMixin:
    """UUID v4 primary key, generated by the database.

    Server-side generation keeps the value correct for rows inserted by
    migrations, workers or psql, not just the ORM.
    """

    @classmethod
    def _pk_name(cls) -> str:
        return f"{cls.__tablename__.rstrip('s')}_id"  # type: ignore[attr-defined]


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class SoftDeleteMixin:
    """Marks rows deleted without removing them.

    Land records are not erasable: a deleted building still has issued
    identifiers pointing at it. Every query in the repositories filters on
    ``deleted_at IS NULL``, matching the partial indexes in 03_indexes.sql.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(nullable=True, default=None)

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None


def uuid_pk(name: str) -> Mapped[uuid.UUID]:
    return mapped_column(
        name,
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
